#initial and start mongodb server

- name: Rendering config parameter file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: mongod
    group: mongod
    mode: 0660
  with_items:
    - { src: 'mongoconf_pro.conf.j2', dest: "/etc/mongod.conf" }
  when: ansible_hostname in groups.mongoconf_{{ env }}

- name: Start mongodb config server
  systemd:
    name: mongod
    state: started
  tags: startup
  when: ansible_hostname in groups.mongoconf_{{ env }}

- name: Initiate config replicaset
  shell: mongo --eval 'rs.initiate({_id:"replconf",members:[{_id:0,host:"mongoc1_{{ env }}:{{ mongodb_port }}"},{_id:1,host:"mongoc2_{{ env }}:{{ mongodb_port }}"},{_id:2,host:"mongoc3_{{ env }}:{{ mongodb_port }}"}]})'
  when: groups.mongodb_{{ env }}.index(inventory_hostname) == 3

- name: Rendering shard parameter file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: mongod
    group: mongod
    mode: 0660
  with_items:
    - { src: 'mongod_shard_pro.conf.j2', dest: "/etc/mongod.conf" }
  when: ansible_hostname in groups.mongoshard_{{ env }}

- name: Modify shard1 parameter file
  lineinfile:
    dest: /etc/mongod.conf
    regexp: "  replSetName: shard0"
    line: "  replSetName: shard1"
  when: groups.mongodb_{{ env }}.index(inventory_hostname) > 8 and groups.mongodb_{{ env }}.index(inventory_hostname) < 12

- name: Modify shard2 parameter file
  lineinfile:
    dest: /etc/mongod.conf
    regexp: "  replSetName: shard0"
    line: "  replSetName: shard2"
  when: groups.mongodb_{{ env }}.index(inventory_hostname) > 11

- name: Start mongodb shard server
  systemd:
    name: mongod
    state: started
  tags: startup
  when: ansible_hostname in groups.mongoshard_{{ env }}

- name: Initiate shard0 replicaset
  shell: mongo --eval 'rs.initiate({_id:"shard0",members:[{_id:0,host:"mongo1_{{ env }}:{{ mongodb_port }}",priority:30},{_id:1,host:"mongo2_{{ env }}:{{ mongodb_port }}",priority:20},{_id:2,host:"mongo3_{{ env }}:{{ mongodb_port }}",priority:10}]})'
  when: groups.mongodb_{{ env }}.index(inventory_hostname) == 6

- name: Initiate shard1 replicaset
  shell: mongo --eval 'rs.initiate({_id:"shard1",members:[{_id:0,host:"mongo4_{{ env }}:{{ mongodb_port }}",priority:20},{_id:1,host:"mongo5_{{ env }}:{{ mongodb_port }}",priority:30},{_id:2,host:"mongo6_{{ env }}:{{ mongodb_port }}",priority:10}]})'
  when: groups.mongodb_{{ env }}.index(inventory_hostname) == 10

- name: Initiate shard2 replicaset
  shell: mongo --eval 'rs.initiate({_id:"shard2",members:[{_id:0,host:"mongo7_{{ env }}:{{ mongodb_port }}",priority:10},{_id:1,host:"mongo8_{{ env }}:{{ mongodb_port }}",priority:20},{_id:2,host:"mongo9_{{ env }}:{{ mongodb_port }}",priority:30}]})'
  when: groups.mongodb_{{ env }}.index(inventory_hostname) == 14

- name: Rendering mongos parameter file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: mongod
    group: mongod
    mode: 0660
  with_items:
    - { src: 'mongos_pro.conf.j2', dest: "/etc/mongod.conf" }
  when: ansible_hostname in groups.mongos_{{ env }}

- name: Modify mongos.server file
  lineinfile:
    dest: "/usr/lib/systemd/system/mongod.service"
    regexp: '/usr/bin/mongod'
    line: 'ExecStart=/usr/bin/numactl --interleave=all /usr/bin/mongos $OPTIONS'
  when: ansible_hostname in groups.mongos_{{ env }}

- name: Daemon reload mongodb server
  systemd:
    daemon_reload: yes

- name: Start mongos server
  systemd:
    name: mongod
    state: started
  tags: startup
  when: ansible_hostname in groups.mongos_{{ env }}

- name: Initiate mongos replicaset
  shell: mongo --eval '{{ item }}'
  with_items:
    - sh.addShard( "shard0/mongo1_{{ env }}:{{ mongodb_port }},mongo2_{{ env }}:{{ mongodb_port }},mongo3_{{ env }}:{{ mongodb_port }}")
    - sh.addShard( "shard1/mongo4_{{ env }}:{{ mongodb_port }},mongo5_{{ env }}:{{ mongodb_port }},mongo6_{{ env }}:{{ mongodb_port }}")
    - sh.addShard( "shard2/mongo7_{{ env }}:{{ mongodb_port }},mongo8_{{ env }}:{{ mongodb_port }},mongo9_{{ env }}:{{ mongodb_port }}")
  when: groups.mongodb_{{ env }}.index(inventory_hostname) == 0

- name: Enable Sharding for a Database
  shell: mongo --eval 'sh.enableSharding("{{ database }}")'
  when: groups.mongodb_{{ env }}.index(inventory_hostname) == 0

- name: Create root user
  mongodb_user:
    login_port: "{{ mongodb_port }}"
    database: admin
    name: root
    password: "{{ root_password }}"
    update_password: always
    roles: root
    state: present
  when: groups.mongodb_{{ env }}.index(inventory_hostname) == 0

- name: Create business user
  mongodb_user:
    login_host: localhost
    login_user: root
    login_password: "{{ root_password }}"
    login_port: "{{ mongodb_port }}"
    database: "{{ database }}"
    name: "{{ business_user }}"
    password: "{{ business_password }}"
    update_password: always
    roles: readWrite
    state: present
  when: groups.mongodb_{{ env }}.index(inventory_hostname) == 0

- name: Create pmm user
  mongodb_user:
    login_host: localhost
    login_user: root
    login_password: "{{ root_password }}"
    login_port: "{{ mongodb_port }}"
    database: admin
    name: pmm
    password: "{{ root_password }}"
    update_password: always
    roles: root
    state: present
  when: groups.mongodb_{{ env }}.index(inventory_hostname) == 0

- name: Create pmm user for local shard0
  mongodb_user:
    login_port: "{{ mongodb_port }}"
    database: admin
    name: pmm
    password: "{{ root_password }}"
    update_password: always
    roles: root
    state: present
  when: groups.mongodb_{{ env }}.index(inventory_hostname) == 6

- name: Create pmm user for local shard1
  mongodb_user:
    login_port: "{{ mongodb_port }}"
    database: admin
    name: pmm
    password: "{{ root_password }}"
    update_password: always
    roles: root
    state: present
  when: groups.mongodb_{{ env }}.index(inventory_hostname) == 10

- name: Create pmm user for local shard2
  mongodb_user:
    login_port: "{{ mongodb_port }}"
    database: admin
    name: pmm
    password: "{{ root_password }}"
    update_password: always
    roles: root
    state: present
  when: groups.mongodb_{{ env }}.index(inventory_hostname) == 14

#- name: Add auth for mongoconf and mongoshard
#  lineinfile:
#    path: "/etc/mongod.conf"
#    regexp: "{{ item.regexp }}"
#    line: "{{ item.line }}"
#  with_items:
#    - { regexp: '^#security', line: 'security:' }
#    - { regexp: '^#  authorization', line: '  authorization: enabled' }
#    - { regexp: '^#  keyFile', line: "  keyFile: {{ keydir }}/keyfile" }
#  when: ansible_hostname in groups.mongoshard_{{ env }} or ansible_hostname in groups.mongoconf_{{ env }}

#- name: Add auth for mongos
#  lineinfile:
#    path: "/etc/mongod.conf"
#    regexp: "{{ item.regexp }}"
#    line: "{{ item.line }}"
#  with_items:
#    - { regexp: '^#security', line: 'security:' }
#    - { regexp: '^#  keyFile', line: "  keyFile: {{ keydir }}/keyfile" }
#  when: ansible_hostname in groups.mongos_{{ env }}

- name: Rendering mongodb backup file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: mongod
    group: mongod
    mode: 0744
  with_items:
    - { src: 'mongodb_backup.sh.j2', dest: "{{ shelldir }}/mongodb_backup.sh" }
    - { src: 'mongodb_restore.sh.j2', dest: "{{ shelldir }}/mongodb_restore.sh" }
    - { src: 'mongodb-consistent-backup.yml.j2', dest: "{{ shelldir }}/mongodb-consistent-backup.yml" }
  when: groups.mongodb_{{ env }}.index(inventory_hostname) == 2

- name: Add the job for backuping mongodb cluster
  cron:
    name: "logrotate"
    minute: "0"
    hour: "1"
    job: "{{ shelldir }}/mongodb_backup.sh 2 > /dev/null 2>&1 &"
  when: groups.mongodb_{{ env }}.index(inventory_hostname) == 2

- name: Stop mongos server
  systemd:
    name: mongod
    state: stopped
  tags: shutdown
  when: ansible_hostname in groups.mongos_{{ env }}

- name: Stop mongodb shard server
  systemd:
    name: mongod
    state: stopped
  tags: shutdown
  when: ansible_hostname in groups.mongoshard_{{ env }}

- name: Stop mongodb config server
  systemd:
    name: mongod
    state: stopped
  tags: shutdown
  when: ansible_hostname in groups.mongoconf_{{ env }}