- name: Copy the percona-release package and mydumper package
  copy:
    src: "{{ item }}"
    dest: "{{ basedir }}"
  with_items:
    - percona-release-0.1-6.noarch.rpm

- name: Install the percona-release package and mydumper package
  yum:
    name: "{{ basedir }}/percona-release-0.1-6.noarch.rpm"
    state: present

- name: Copy the percona-release.repo
  copy: src=percona-release.repo dest=/etc/yum.repos.d/percona-release.repo

- name: Install the percona tools
  yum:
    name: "{{ tools }}"
  vars:
    tools:
    - pmm-client.x86_64
    state: latest
  register: result
  retries: 7
  until: result is succeeded