---
# tasks file for dba_ray.mongodb
- include: password.yml
  when: ( is_standalone | default(False) ) or ( is_replica_set | default(False) )

- include: initial_start.yml
  when: is_standalone | default(False)

- include: initial_replica_set.yml
  when: ( is_standalone | default(False) ) and ( is_replica_set | default(False) )