# Detection system to eliminate interference

- name: Disable firewalld
  service: name=firewalld state=stopped enabled=no

- name: Disable selinux forever
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

- name: Uninsatll mariadb on the system
  yum:
    name: mariadb
    state: absent

- name: Disable kernel hugepage
  shell: "echo never > /sys/kernel/mm/transparent_hugepage/enabled;echo never > /sys/kernel/mm/transparent_hugepage/defrag"

- name: Disable swap
  sysctl:
    name: vm.swappiness
    value: '0'
    sysctl_file: /etc/sysctl.conf
    state: present
    reload: yes

- name: Disable file system atime
  mount:
    path: "{{ install_dir }}"
    src: "{{ fstab_src }}"
    fstype: ext4
    opts: noatime
    state: present
    backup: yes

- name: Remount file path
  mount:
    path: "{{ install_dir }}"
    src: "{{ fstab_src }}"
    fstype: ext4
    opts: noatime
    state: remounted

- name: Install base packages
  yum:
    name: "{{ packages }}"
    state: latest

- name: Install pymongo
  pip:
    name: pymongo
    state: latest

- name: Stop mongodb server
  systemd:
    name: mongod
    state: stopped
  when: whether_uninstall

#- name: Uninsatll mongodb
#  yum:
#    name: mongodb-org
#    state: absent
#  when: whether_uninstall

- name: Remove existing mongodb directory
  file:
    path: "{{ basedir }}"
    state: absent
    remote_src: 'True'
  when: whether_uninstall

#- name: Update all packages
#  yum:
#    name: '*'
#    state: latest